package br.com.view;

import br.com.control.CargoControl;
import br.com.control.PerfilControl;
import br.com.control.UsuarioControl;
import br.com.model.Cargo;
import br.com.model.Perfil;
import br.com.model.Usuario;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class DialogoUsuario extends javax.swing.JDialog {

    private static CargoControl cargoControl;
    private static PerfilControl perfilControl;
    private static UsuarioControl usuarioControl;
    private Usuario usuarioOriginal;
    
    /**
     * Creates new form NewJDialog
     */
    public DialogoUsuario(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        preparar(usuario);
    }
    
    private void preparar(Usuario usuario) {
        cargoControl = CargoControl.getInstancia();
        perfilControl = PerfilControl.getInstancia();
        usuarioControl = UsuarioControl.getInstancia();
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel(cargoControl.getCargoNames()));
        Integer[] dias = new Integer[111];
        for (int i = 0; i < 111; i++) {
            dias[i] = i + 1900;
        }
        comboAno.setModel(new DefaultComboBoxModel(dias));
        comboMes.addItemListener(this::comboDataChanged);
        comboAno.addItemListener(this::comboDataChanged);
        updateLista(listPerfil, perfilControl.getPerfilNames());
        if (usuario == null) {
            this.setTitle("Novo usuário");
            botaoProsseguir.setText("Adicionar Usuário");
        } else {
            this.setTitle(usuario.getNome() + " - Registrado em " + usuario.getDataCriado());
            botaoProsseguir.setText("Alterar Usuário");
            usuarioOriginal = usuario;
            carregarUsuario(usuario);
        }
    }
    
    private void updateLista(JList lista, String[] valores) {
        lista.removeAll();
        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = valores;

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
    }
    
    private void comboDataChanged(ItemEvent e) {
        if (e == null || e.getStateChange() == ItemEvent.SELECTED) {
            int dia = comboDia.getSelectedIndex() + 1;
            int mes = comboMes.getSelectedIndex() + 1;
            int ano = comboAno.getSelectedIndex() + 1900;
            int maxDias = 30;
            if (mes == 2) {
                if (ano % 4 == 0) {
                    maxDias = 29;
                } else {
                    maxDias = 28;
                }
            } else if ((mes < 6 && mes % 2 == 1)
                     || mes > 6 && mes % 2 == 0) {
                maxDias = 31;
            }
            Integer[] dias = new Integer[maxDias];
            for (int i = 0; i < maxDias; i++) {
                dias[i] = i + 1;
            }
            comboDia.setModel(new DefaultComboBoxModel(dias));
            if (dia > maxDias) {
                comboDia.setSelectedIndex(maxDias - 1);
            } else {
                comboDia.setSelectedIndex(dia - 1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPerfil = new javax.swing.JList();
        botaoProsseguir = new javax.swing.JButton();
        comboDia = new javax.swing.JComboBox();
        comboMes = new javax.swing.JComboBox();
        comboAno = new javax.swing.JComboBox();
        labelWarnNome = new javax.swing.JLabel();
        labelWarnCpf = new javax.swing.JLabel();
        labelWarnPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Nascimento:");

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Masculino", "Feminino" }));

        jLabel4.setText("Sexo:");

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Cargo:");

        jLabel6.setText("Perfis:");

        listPerfil.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPerfil);

        botaoProsseguir.setText("Usuário");
        botaoProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProsseguirActionPerformed(evt);
            }
        });

        comboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        comboAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000" }));

        labelWarnNome.setForeground(new java.awt.Color(255, 0, 0));

        labelWarnCpf.setForeground(new java.awt.Color(255, 0, 0));

        labelWarnPerfil.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelWarnNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelWarnCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(botaoProsseguir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelWarnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboCargo, 0, 120, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWarnNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWarnCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(labelWarnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoProsseguir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProsseguirActionPerformed
        String nome = campoNome.getText();
        String cpf = campoCpf.getText().trim();
        int dia = comboDia.getSelectedIndex() + 1;
        int mes = comboMes.getSelectedIndex() + 1;
        int ano = comboAno.getSelectedIndex() + 1;
        char sexo = (char) comboSexo.getSelectedIndex();
        Date data = new Date(ano, mes, dia);
        Cargo cargo = cargoControl.getByNome((String) comboCargo.getSelectedItem());
        List<Perfil> perfis = getPerfis();
        boolean ok = validar(nome, cpf);
        if (ok) {
            labelWarnCpf.setText("");
            labelWarnNome.setText("");
            labelWarnPerfil.setText("");
            if (usuarioOriginal == null) {
                usuarioControl.addUsuario(nome, cpf, data, sexo, cargo, perfis);
                JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso!", "Adicionar usuário", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário alterado!", "Alterar usuário", JOptionPane.INFORMATION_MESSAGE);
                usuarioControl.updateUsuario(usuarioOriginal.getCpf(), nome, cpf, data, sexo, cargo, perfis);
                this.dispose();
            }
        }
    }//GEN-LAST:event_botaoProsseguirActionPerformed

    private boolean validar(String nome, String cpf) {
        boolean ok = true;
        if (nome.trim().equals("")) {
            ok = false;
            labelWarnNome.setText("Insira o nome");
        } else {
            labelWarnNome.setText("");
        }
        if (cpf.trim().equals("")) {
            ok = false;
            labelWarnCpf.setText("Insira o CPF");
        } else if (usuarioControl.getByCPF(cpf) != null) {
            if (usuarioOriginal != null && !cpf.equalsIgnoreCase(usuarioOriginal.getCpf())) {
                ok = false;
                labelWarnCpf.setText("Já existe");
            }
        } else {
            labelWarnCpf.setText("");
        }
        if (listPerfil.getSelectedValuesList().isEmpty()) {
            ok = false;
            labelWarnPerfil.setText("Escolha pelo menos 1 item abaixo");
        } else {
            labelWarnPerfil.setText("");
        }
        return ok;
    }
    
    private List<Perfil> getPerfis() {
        List<String> perfilNomes = listPerfil.getSelectedValuesList();
        List<Perfil> perfis = new ArrayList<>();
        for (String perfilNome : perfilNomes) {
            perfis.add(perfilControl.getByNome(perfilNome));
        }
        return perfis;
    }
    
    private void carregarUsuario(Usuario usuario) {
        campoNome.setText(usuario.getNome());
        campoCpf.setText(usuario.getCpf());
        comboAno.setSelectedIndex(usuario.getDatanasc().getYear() - 1);
        comboMes.setSelectedIndex(usuario.getDatanasc().getMonth() - 1);
        comboDataChanged(null);
        comboDia.setSelectedIndex(usuario.getDatanasc().getDate() - 1);
        comboSexo.setSelectedIndex(usuario.getSexo());
        
        String cargo = usuario.getCargo().getNome();
        for (int i = 0; i < comboCargo.getModel().getSize(); i++) {
            if (cargo.equals((String) comboCargo.getModel().getElementAt(i))) {
                comboCargo.setSelectedIndex(i);
            }
        }
        
        String[] perfis = usuario.getListaPerfis();
        int[] indicesPerfil = new int[perfis.length];
        for (int i = 0; i < perfis.length; i++) {
            for (int j = 0; j < listPerfil.getModel().getSize(); j++) {
                if (perfis[i].equals((String) listPerfil.getModel().getElementAt(j))) {
                    indicesPerfil[i] = j;
                    break;
                }
            }
        }
        listPerfil.setSelectedIndices(indicesPerfil);
    }
    
    public static void adicionarUsuario(Frame parent) {
        DialogoUsuario dialog = new DialogoUsuario(parent, true, null);
        dialog.setVisible(true);
    }
    
    public static void alterarUsuario(Frame parent, Usuario usuario) {
        DialogoUsuario dialog = new DialogoUsuario(parent, true, usuario);
        dialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoUsuario dialog = new DialogoUsuario(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProsseguir;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox comboAno;
    private javax.swing.JComboBox comboCargo;
    private javax.swing.JComboBox comboDia;
    private javax.swing.JComboBox comboMes;
    private javax.swing.JComboBox comboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelWarnCpf;
    private javax.swing.JLabel labelWarnNome;
    private javax.swing.JLabel labelWarnPerfil;
    private javax.swing.JList listPerfil;
    // End of variables declaration//GEN-END:variables
}
