package br.com.view;

import br.com.control.CargoControl;
import br.com.control.PerfilControl;
import br.com.control.UsuarioControl;
import br.com.model.Usuario;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class GerenciadorWindow extends javax.swing.JFrame {

    /**
     * Creates new form GerenciadorWindow
     */
    CargoControl cargoControl;
    PerfilControl perfilControl;
    UsuarioControl usuarioControl;
    
    
    public GerenciadorWindow() {
        cargoControl = CargoControl.getInstancia();
        perfilControl = PerfilControl.getInstancia();
        usuarioControl = UsuarioControl.getInstancia();
        initComponents();
        refresh();
        this.setLocationRelativeTo(null);
    }

    private void refresh() {
        updateLista(listCargos, cargoControl.getCargoNames());
        updateLista(listPerfis, perfilControl.getPerfilNames());
        updateLista(listUsuarios, usuarioControl.getUsuarioNames());
        updateContadores();
    }
    
    private void updateContadores() {
        labelContCargo.setText(cargoControl.countCargos() + "");
        labelContPerfil.setText(perfilControl.countPerfis() + "");
        labelContUsuario.setText(usuarioControl.countUsuarios() + "");
    }
    
    private void updateLista(JList lista, String[] valores) {
        lista.removeAll();
        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = valores;

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
    }
    
    private int selecionarOpcao() {
        String[] opcoes = {"Editar", "Excluir"};
        int opcao = -1;
        try {
            opcao = JOptionPane.showOptionDialog(null, "Deseja editar ou excluir este item?", 
                    "Opções", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, 0);
        } catch (Exception e) {
            
        }
        return opcao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelContCargo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelContPerfil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelContUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCargos = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPerfis = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Cargos cadastrados:");

        labelContCargo.setText("0");

        jLabel5.setText("Perfis cadastrados:");

        labelContPerfil.setText("0");

        jLabel6.setText("Usuários cadastrados:");

        labelContUsuario.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelContCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelContPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addComponent(labelContUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelContCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelContPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelContUsuario))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jLabel1.setText("Todos os cargos registrados (clique 2x para opções):");

        listCargos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCargos);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cargos", jPanel2);

        jLabel2.setText("Todos os perfis registrados (clique 2x para opções):");

        listPerfis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPerfis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPerfisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listPerfis);

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Perfis", jPanel3);

        jLabel3.setText("Todos os usuários registrados (clique 2x para opções):");

        listUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listUsuarios);

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuários", jPanel4);

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCargosMouseClicked
        if (evt.getClickCount() == 2) {
            System.out.println(listCargos.getSelectedValue());
            int opcao = selecionarOpcao();
            if (opcao == 0) {
                editarCargo();
            } else if (opcao == 1) {
                excluirCargo();
            }
        }
    }//GEN-LAST:event_listCargosMouseClicked

    private void editarCargo() {
        String nome = (String) listCargos.getSelectedValue();
        String novoNome = (String) JOptionPane.showInputDialog(null, "Insira o nome do cargo:", 
                "Editar cargo", JOptionPane.QUESTION_MESSAGE, null, null, nome);
        if (novoNome != null && !novoNome.trim().equals("") && !nome.equalsIgnoreCase(novoNome)) {
            if (cargoControl.updateCargo(nome, novoNome)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Cargo alterado!", "Editar cargo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse cargo já existe!", "Editar cargo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    public void excluirCargo() {
        int opcao = -1;
        try {
            opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse cargo?", 
                    "Excluir cargo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
        }
        if (opcao == JOptionPane.YES_OPTION) {
            if (cargoControl.deleteCargo((String) listCargos.getSelectedValue())) {
                refresh();
                JOptionPane.showMessageDialog(null, "Cargo excluído!", "Excluir cargo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse cargo está em uso!", "Excluir cargo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    private void editarPerfil() {
        String nome = (String) listPerfis.getSelectedValue();
        String novoNome = (String) JOptionPane.showInputDialog(null, "Insira o nome do perfil:", 
                "Editar perfil", JOptionPane.QUESTION_MESSAGE, null, null, nome);
        if (novoNome != null && !novoNome.trim().equals("") && !nome.equalsIgnoreCase(novoNome)) {
            if (perfilControl.updatePerfil(nome, novoNome)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Perfil alterado!", "Editar perfil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse perfil já existe!", "Editar perfil", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    public void excluirPerfil() {
        int opcao = -1;
        try {
            opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse perfil?", 
                    "Excluir perfil", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
        }
        if (opcao == JOptionPane.YES_OPTION) {
            if (perfilControl.deletePerfil((String) listPerfis.getSelectedValue())) {
                refresh();
                JOptionPane.showMessageDialog(null, "Perfil excluído!", "Excluir perfil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse perfil está em uso!", "Excluir perfil", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String novoCargo = JOptionPane.showInputDialog(null, "Insira o nome do cargo:", "Novo cargo", JOptionPane.QUESTION_MESSAGE);
        if (novoCargo != null && !novoCargo.trim().equals("")) {
            if (cargoControl.addCargo(novoCargo)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Cargo criado com sucesso!", "Novo cargo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse cargo já existe!", "Novo cargo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listPerfisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPerfisMouseClicked
        if (evt.getClickCount() == 2) {
            System.out.println(listPerfis.getSelectedValue());
            int opcao = selecionarOpcao();
            if (opcao == 0) {
                editarPerfil();
            } else if (opcao == 1) {
                excluirPerfil();
            }
        }
    }//GEN-LAST:event_listPerfisMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String novoPerfil = JOptionPane.showInputDialog(null, "Insira o nome do perfil:", "Novo perfil", JOptionPane.QUESTION_MESSAGE);
        if (novoPerfil != null && !novoPerfil.trim().equals("")) {
            if (perfilControl.addPerfil(novoPerfil)) {
                refresh();
                JOptionPane.showMessageDialog(null, "Perfil criado com sucesso!", "Novo perfil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Esse perfil já existe!", "Novo perfil", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsuariosMouseClicked
        if (evt.getClickCount() == 2 && listUsuarios.getSelectedIndex() >= 0) {
            System.out.println(listUsuarios.getSelectedValue());
            String[] exploded = listUsuarios.getSelectedValue().toString().split(" ");
            int cpfPos = exploded.length - 1;
            String cpf = exploded[cpfPos];
            int opcao = selecionarOpcao();
            if (opcao == 0) {
                Usuario usuario = usuarioControl.getByCPF(cpf);
                DialogoUsuario.alterarUsuario(this, usuario);
                refresh();
            } else if (opcao == 1) {
                opcao = -1;
                try {
                    opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse usuário?",
                            "Excluir usuário", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                } catch (Exception e) {
                }
                if (opcao == JOptionPane.YES_OPTION && usuarioControl.deleteUsuario(cpf)) {
                    refresh();
                    JOptionPane.showMessageDialog(null, "Usuário excluído!", "Excluir usuário", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_listUsuariosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DialogoUsuario.adicionarUsuario(this);
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelContCargo;
    private javax.swing.JLabel labelContPerfil;
    private javax.swing.JLabel labelContUsuario;
    private javax.swing.JList listCargos;
    private javax.swing.JList listPerfis;
    private javax.swing.JList listUsuarios;
    // End of variables declaration//GEN-END:variables
}
